name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.6.0"
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-ci-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: npm ci
        run: npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'
      - name: install playwright dependencies
        run: cd e2e && npx playwright install-deps
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run e2e
